// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxM2S06g-V0hrc-LjUgVUzId0dWyNhtrE',
    appId: '1:374880543559:web:56eb6c65d36bc55b736262',
    messagingSenderId: '374880543559',
    projectId: 'damystrio',
    authDomain: 'damystrio.firebaseapp.com',
    storageBucket: 'damystrio.firebasestorage.app',
    measurementId: 'G-XFTLVF0XWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8IP0vsr_pjlJnAe7SOSyX8uKHm2OarLk',
    appId: '1:374880543559:android:e7b866b277c7c7c9736262',
    messagingSenderId: '374880543559',
    projectId: 'damystrio',
    storageBucket: 'damystrio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2pLRvz44RaiItzlNC3lyVp3WERQarZtg',
    appId: '1:374880543559:ios:178580423314e44f736262',
    messagingSenderId: '374880543559',
    projectId: 'damystrio',
    storageBucket: 'damystrio.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2pLRvz44RaiItzlNC3lyVp3WERQarZtg',
    appId: '1:374880543559:ios:178580423314e44f736262',
    messagingSenderId: '374880543559',
    projectId: 'damystrio',
    storageBucket: 'damystrio.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxM2S06g-V0hrc-LjUgVUzId0dWyNhtrE',
    appId: '1:374880543559:web:e3a1d49c4429331d736262',
    messagingSenderId: '374880543559',
    projectId: 'damystrio',
    authDomain: 'damystrio.firebaseapp.com',
    storageBucket: 'damystrio.firebasestorage.app',
    measurementId: 'G-09YV38Q2DX',
  );
}
