// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgZfduF2M97IxsstDl9gneBgFWXg1ooL8',
    appId: '1:813391034255:web:0a2269474639c64aa17dfa',
    messagingSenderId: '813391034255',
    projectId: 'bank-co-61d86',
    authDomain: 'bank-co-61d86.firebaseapp.com',
    databaseURL: 'https://bank-co-61d86-default-rtdb.firebaseio.com',
    storageBucket: 'bank-co-61d86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV-0aRzrn1be9hpodmScqeo8rIn5pySC4',
    appId: '1:813391034255:android:dbb1f60c41416223a17dfa',
    messagingSenderId: '813391034255',
    projectId: 'bank-co-61d86',
    databaseURL: 'https://bank-co-61d86-default-rtdb.firebaseio.com',
    storageBucket: 'bank-co-61d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaJsF3m9kOhHTUqQonQ4q5BB5Jv9XEvZw',
    appId: '1:813391034255:ios:0c87b019d3e51874a17dfa',
    messagingSenderId: '813391034255',
    projectId: 'bank-co-61d86',
    databaseURL: 'https://bank-co-61d86-default-rtdb.firebaseio.com',
    storageBucket: 'bank-co-61d86.firebasestorage.app',
    iosClientId: '813391034255-6irptsa7372ico8rjn7eobok2emchek3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaJsF3m9kOhHTUqQonQ4q5BB5Jv9XEvZw',
    appId: '1:813391034255:ios:0c87b019d3e51874a17dfa',
    messagingSenderId: '813391034255',
    projectId: 'bank-co-61d86',
    databaseURL: 'https://bank-co-61d86-default-rtdb.firebaseio.com',
    storageBucket: 'bank-co-61d86.firebasestorage.app',
    iosClientId: '813391034255-6irptsa7372ico8rjn7eobok2emchek3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgZfduF2M97IxsstDl9gneBgFWXg1ooL8',
    appId: '1:813391034255:web:8419eff41a1777cba17dfa',
    messagingSenderId: '813391034255',
    projectId: 'bank-co-61d86',
    authDomain: 'bank-co-61d86.firebaseapp.com',
    databaseURL: 'https://bank-co-61d86-default-rtdb.firebaseio.com',
    storageBucket: 'bank-co-61d86.firebasestorage.app',
  );

}